# Atividade 01 - Análise Exploratória de Dados (EDA)
## Análise do Dataframe do Titanic

**Integrantes:** Mauro Roberto Barbosa Cahu, Pedro Paulo Sant'Anna Belo Ramos, Renato Vasconcellos Bittencourt Neto e Vinicius Dantas Batista da Silva

## Atividade Solicitada
O objetivo deste estudo é aplicar transformações, normalizações e análises descritivas e estatísticas dos dados. Por fim, é preciso que seja feita uma conclusão do estudo realizado.

Base de dados utilizada: Titanic
1. Carregamento de dados
2. Análise dos dados
3. Transformação dos dados (categoricos/binarização)
2. Remoção de campos desnecessários (nome, id, ticket, cabine)
4. Tratamento de dados nulos e/ou faltantes
5. Separação dos dados, holdout
6. Normalização dos dados

## Importar bibliotecas
**Importe pandas, seaborn e as bibliotecas usuais.**

In [520]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### Obtenha os dados
**Leia o arquivo csv 'titanic.csv' em um DataFrame**

In [521]:
df = pd.read_csv('https://raw.githubusercontent.com/agconti/kaggle-titanic/master/data/train.csv')

**Verifique o cabeçalho do DataFrame**

In [522]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [523]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [524]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## Transformação dos dados (categoricos/binarização)

### Categorização

In [525]:
from sklearn import preprocessing

In [526]:
le = preprocessing.LabelEncoder()

In [527]:
le.fit(df['Sex'])

LabelEncoder()

In [528]:
df['Sex_le'] = le.transform(df['Sex'])

In [529]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_le
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1

In [530]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

### Binarização

In [531]:
df_Embarked = pd.get_dummies(df, columns=['Embarked'], drop_first=True, dtype=int)
display(df_Embarked.head(10))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex_le,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,1,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,0,0,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,0,0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,1,0,1
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,1,1,0
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,1,0,1
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,1,0,1
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,0,0,1
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,0,0,0

### Remoção de campos desnecessários (PassengerId, Name, Ticket, Cabin)

In [532]:
df_Embarked.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True, errors='ignore')
display(df_Embarked.head())

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Sex_le,Embarked_Q,Embarked_S
0,0,3,male,22.0,1,0,7.2500,1,0,1
1,1,1,female,38.0,1,0,71.2833,0,0,0
2,1,3,female,26.0,0,0,7.9250,0,0,1
3,1,1,female,35.0,1,0,53.1000,0,0,1
4,0,3,male,35.0,0,0,8.0500,1,0,1

In [533]:
display(df_Embarked.head())

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Sex_le,Embarked_Q,Embarked_S
0,0,3,male,22.0,1,0,7.2500,1,0,1
1,1,1,female,38.0,1,0,71.2833,0,0,0
2,1,3,female,26.0,0,0,7.9250,0,0,1
3,1,1,female,35.0,1,0,53.1000,0,0,1
4,0,3,male,35.0,0,0,8.0500,1,0,1

## Tratamento de dados nulos e/ou faltantes

Describe

In [534]:
df_Embarked.describe()

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_le,Embarked_Q,Embarked_S
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,0.647587,0.086420,0.722783
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,0.477990,0.281141,0.447876
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400,0.000000,0.000000,0.000000
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,1.000000,0.000000,1.000000
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,1.000000,0.000000,1.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,1.000000,1.000000,1.000000

Male

In [535]:
# Preenchendo idades nulas com base na mediana de cada classe

df_Embarked.loc[df_Embarked.Age.isna() & (df_Embarked.Pclass == 1) & (df_Embarked.Sex == 'male'), 'Age'] = df_Embarked[(df_Embarked.Pclass == 1) & (df_Embarked.Sex == 'male')].Age.median()
df_Embarked.loc[df_Embarked.Age.isna() & (df_Embarked.Pclass == 2) & (df_Embarked.Sex == 'male'), 'Age'] = df_Embarked[(df_Embarked.Pclass == 2) & (df_Embarked.Sex == 'male')].Age.median()
df_Embarked.loc[df_Embarked.Age.isna() & (df_Embarked.Pclass == 3) & (df_Embarked.Sex == 'male'), 'Age'] = df_Embarked[(df_Embarked.Pclass == 3) & (df_Embarked.Sex == 'male')].Age.median()

Female

In [536]:
df_Embarked.loc[df_Embarked.Age.isna() & (df_Embarked.Pclass == 1) & (df_Embarked.Sex == 'female'), 'Age'] = df_Embarked[(df_Embarked.Pclass == 1) & (df_Embarked.Sex == 'female')].Age.median()
df_Embarked.loc[df_Embarked.Age.isna() & (df_Embarked.Pclass == 2) & (df_Embarked.Sex == 'female'), 'Age'] = df_Embarked[(df_Embarked.Pclass == 2) & (df_Embarked.Sex == 'female')].Age.median()
df_Embarked.loc[df_Embarked.Age.isna() & (df_Embarked.Pclass == 3) & (df_Embarked.Sex == 'female'), 'Age'] = df_Embarked[(df_Embarked.Pclass == 3) & (df_Embarked.Sex == 'female')].Age.median()

Removendo os dados nulos remanencentes

In [537]:
print("Nulos antes da remoção:")
display(df_Embarked.isnull().sum())

Nulos antes da remoção:

Survived      0
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Sex_le        0
Embarked_Q    0
Embarked_S    0
dtype: int64

## Separação dos dados, holdout

Use o método train_test_split para dividir seus dados em um conjunto treino e teste.

Removendo a coluna Sex pois não será utilizada para treinar o modelo

In [538]:
df_Embarked.drop(columns=['Sex'], inplace=True)

In [539]:
from sklearn.model_selection import train_test_split

In [540]:
X_train, X_test, y_train, y_test = train_test_split(df_Embarked.drop(columns=['Survived']),
                                                    df_Embarked['Survived'],
                                                    test_size=0.3,
                                                    random_state=111)

In [541]:
pd.DataFrame(X_train)

     Pclass   Age  SibSp  Parch      Fare  Sex_le  Embarked_Q  Embarked_S
195       1  58.0      0      0  146.5208       0           0           0
150       2  51.0      0      0   12.5250       1           0           1
572       1  36.0      0      0   26.3875       1           0           1
134       2  25.0      0      0   13.0000       1           0           1
96        1  71.0      0      0   34.6542       1           0           0
..      ...   ...    ...    ...       ...     ...         ...         ...
275       1  63.0      1      0   77.9583       0           0           1
86        3  16.0      1      3   34.3750       1           0           1
724       1  27.0      1      0   53.1000       1           0           1
876       3  20.0      0      0    9.8458       1           0           1
852       3   9.0      1      1   15.2458       0           0           0

[623 rows x 8 columns]

In [542]:
pd.DataFrame(X_test)

     Pclass   Age  SibSp  Parch      Fare  Sex_le  Embarked_Q  Embarked_S
374       3   3.0      3      1   21.0750       0           0           1
211       2  35.0      0      0   21.0000       0           0           1
258       1  35.0      0      0  512.3292       0           0           0
584       3  25.0      0      0    8.7125       1           0           0
461       3  34.0      0      0    8.0500       1           0           1
..      ...   ...    ...    ...       ...     ...         ...         ...
383       1  35.0      1      0   52.0000       0           0           1
719       3  33.0      0      0    7.7750       1           0           1
291       1  19.0      1      0   91.0792       0           0           0
432       2  42.0      1      0   26.0000       0           0           1
228       2  18.0      0      0   13.0000       1           0           1

[268 rows x 8 columns]

## Normalização dos dados

Hora de para padronizar as variáveis.

Import StandardScaler do Scikit-learn.

Converta as variáveis independentes com o StandardScaler;

Use o método .transform () para transformar os parâmetros em uma versão padronizada.

####Normalização do Fare e Age

In [543]:
from sklearn.preprocessing import StandardScaler

fare_scaler = StandardScaler()
age_scaler = StandardScaler()

# Para os dados de Treino
X_train_fare = X_train[["Fare"]]
X_train_age = X_train[["Age"]]

X_train_fare_scaled = fare_scaler.fit_transform(X_train[["Fare"]])
X_train_age_scaled = age_scaler.fit_transform(X_train[["Age"]])

# Para dados de Teste
X_test_fare = X_test[["Fare"]]
X_test_age = X_test[["Age"]]

X_test_fare_scaled = fare_scaler.transform(X_test[["Fare"]])
X_test_age_scaled = age_scaler.transform(X_test[["Age"]])

print('Dados Treino do Fare')
display(X_train_fare_scaled[:10])
print('\nDados do Treino do Age')
display(X_train_age_scaled[:10])

print('\nDados Teste do Fare')
display(X_test_fare_scaled[:10])
print('\nDados do Teste do Age')
display(X_test_age_scaled[:10])

Dados Treino do Fare

array([[ 2.50734839],
       [-0.4091286 ],
       [-0.10740524],
       [-0.39879002],
       [ 0.07252309],
       [-0.22303412],
       [ 1.0150557 ],
       [-0.51305855],
       [ 0.52497208],
       [ 0.22324873]])

Dados do Treino do Age

array([[ 2.1102145 ],
       [ 1.59580797],
       [ 0.49350825],
       [-0.31484487],
       [ 3.06554092],
       [-1.56411788],
       [-0.60879146],
       [-0.57204814],
       [-0.31484487],
       [-1.93155112]])

Dados Teste do Fare

array([[-0.22303412],
       [-0.22466653],
       [10.46932767],
       [-0.49210932],
       [-0.50652892],
       [-0.68174068],
       [ 0.18207505],
       [-0.02877761],
       [-0.53246679],
       [-0.11583935]])

Dados do Teste do Age

array([[-1.93155112],
       [ 0.4200216 ],
       [ 0.4200216 ],
       [-0.31484487],
       [ 0.34653496],
       [ 0.78745484],
       [-2.00503777],
       [-0.75576476],
       [-0.31484487],
       [ 0.27304831]])

In [544]:
# Criação do dataframes temporarios para as informações de treino escaladas de Fare e Age
db_x_train_fare = pd.DataFrame(X_train_fare_scaled, index=X_train.index)
db_x_train_fare = db_x_train_fare.rename(columns={0: 'Fare_scaled'})

db_x_train_age = pd.DataFrame(X_train_age_scaled, index=X_train.index)
db_x_train_age = db_x_train_age.rename(columns={0: 'Age_scaled'})

# Concatenação no X_train_scaled, as informações das colunas scaled
X_train_scaled = X_train.copy()
X_train_scaled = pd.concat([X_train_scaled, db_x_train_fare], axis = 1)
X_train_scaled = pd.concat([X_train_scaled, db_x_train_age], axis = 1)

# Criação do dataframes temporarios para as informações de teste escaladas de Fare e Age
db_x_test_fare = pd.DataFrame(X_test_fare_scaled, index=X_test.index)
db_x_test_fare = db_x_test_fare.rename(columns={0: 'Fare_scaled'})

db_x_test_age = pd.DataFrame(X_test_age_scaled, index=X_test.index)
db_x_test_age = db_x_test_age.rename(columns={0: 'Age_scaled'})

# Concatenação no X_test_scaled, as informações das colunas scaled
X_test_scaled = X_test.copy()
X_test_scaled = pd.concat([X_test_scaled, db_x_test_fare], axis = 1)
X_test_scaled = pd.concat([X_test_scaled, db_x_test_age], axis = 1)

In [545]:
print('\nDados Originais de Treino')
display(X_train)

print('\nDados Escalados de Treino')
display(X_train_scaled)

Dados Originais de Treino

     Pclass   Age  SibSp  Parch      Fare  Sex_le  Embarked_Q  Embarked_S
195       1  58.0      0      0  146.5208       0           0           0
150       2  51.0      0      0   12.5250       1           0           1
572       1  36.0      0      0   26.3875       1           0           1
134       2  25.0      0      0   13.0000       1           0           1
96        1  71.0      0      0   34.6542       1           0           0
..      ...   ...    ...    ...       ...     ...         ...         ...
275       1  63.0      1      0   77.9583       0           0           1
86        3  16.0      1      3   34.3750       1           0           1
724       1  27.0      1      0   53.1000       1           0           1
876       3  20.0      0      0    9.8458       1           0           1
852       3   9.0      1      1   15.2458       0           0           0

[623 rows x 8 columns]

Dados Escalados de Treino

,Pclass,Age,SibSp,Parch,Fare,Sex_le,Embarked_Q,Embarked_S,Fare_scaled,Age_scaled
195,1,58.0,0,0,146.5208,0,0,0,2.507348,2.110215
150,2,51.0,0,0,12.5250,1,0,1,-0.409129,1.595808
572,1,36.0,0,0,26.3875,1,0,1,-0.107405,0.493508
134,2,25.0,0,0,13.0000,1,0,1,-0.398790,-0.314845
96,1,71.0,0,0,34.6542,1,0,0,0.072523,3.065541
...,...,...,...,...,...,...,...,...,...,...
275,1,63.0,1,0,77.9583,0,0,1,1.015056,2.477648
86,3,16.0,1,3,34.3750,1,0,1,0.066446,-0.976225
724,1,27.0,1,0,53.1000,1,0,1,0.474004,-0.167872
876,3,20.0,0,0,9.8458,1,0,1,-0.467443,-0.682278
852,3,9.0,1,1,15.2458,0,0,0,-0.349909,-1.490631

In [546]:
print('\nDados Originais de Teste')
display(X_test)

print('\nDados Escalados de Teste')
display(X_test_scaled)

Dados Originais de Teste

     Pclass   Age  SibSp  Parch      Fare  Sex_le  Embarked_Q  Embarked_S
374       3   3.0      3      1   21.0750       0           0           1
211       2  35.0      0      0   21.0000       0           0           1
258       1  35.0      0      0  512.3292       0           0           0
584       3  25.0      0      0    8.7125       1           0           0
461       3  34.0      0      0    8.0500       1           0           1
..      ...   ...    ...    ...       ...     ...         ...         ...
383       1  35.0      1      0   52.0000       0           0           1
719       3  33.0      0      0    7.7750       1           0           1
291       1  19.0      1      0   91.0792       0           0           0
432       2  42.0      1      0   26.0000       0           0           1
228       2  18.0      0      0   13.0000       1           0           1

[268 rows x 8 columns]

Dados Escalados de Teste

,Pclass,Age,SibSp,Parch,Fare,Sex_le,Embarked_Q,Embarked_S,Fare_scaled,Age_scaled
374,3,3.0,3,1,21.0750,0,0,1,-0.223034,-1.931551
211,2,35.0,0,0,21.0000,0,0,1,-0.224667,0.420022
258,1,35.0,0,0,512.3292,0,0,0,10.469328,0.420022
584,3,25.0,0,0,8.7125,1,0,0,-0.492109,-0.314845
461,3,34.0,0,0,8.0500,1,0,1,-0.506529,0.346535
...,...,...,...,...,...,...,...,...,...,...
383,1,35.0,1,0,52.0000,0,0,1,0.450062,0.420022
719,3,33.0,0,0,7.7750,1,0,1,-0.512514,0.273048
291,1,19.0,1,0,91.0792,0,0,0,1.300638,-0.755765
432,2,42.0,1,0,26.0000,0,0,1,-0.115839,0.934428
228,2,18.0,0,0,13.0000,1,0,1,-0.398790,-0.829251

In [547]:
print('\nInfo Originais de Treino')
display(X_train.info())

print('\nInfo Escalados de Treino')
display(X_train_scaled.info())

Info Originais de Treino
<class 'pandas.core.frame.DataFrame'>
Index: 623 entries, 195 to 852
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Pclass      623 non-null    int64
 1   Age         623 non-null    float64
 2   SibSp       623 non-null    int64
 3   Parch       623 non-null    int64
 4   Fare        623 non-null    float64
 5   Sex_le      623 non-null    int64
 6   Embarked_Q  623 non-null    int64
 7   Embarked_S  623 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 43.8 KB

None

Info Escalados de Treino
<class 'pandas.core.frame.DataFrame'>
Index: 623 entries, 195 to 852
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Pclass       623 non-null    int64
 1   Age          623 non-null    float64
 2   SibSp        623 non-null    int64
 3   Parch        623 non-null    int64
 4   Fare         623 non-null    float64
 5   Sex_le       623 non-null    int64
 6   Embarked_Q   623 non-null    int64
 7   Embarked_S   623 non-null    int64
 8   Fare_scaled  623 non-null    float64
 9   Age_scaled   623 non-null    float64
dtypes: float64(4), int64(6)
memory usage: 53.5 KB

None

In [548]:
print('\nInfo Originais de Teste')
display(X_test.info())

print('\nInfo Escalados de Teste')
display(X_test_scaled.info())

Info Originais de Teste
<class 'pandas.core.frame.DataFrame'>
Index: 268 entries, 374 to 228
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Pclass      268 non-null    int64
 1   Age         268 non-null    float64
 2   SibSp       268 non-null    int64
 3   Parch       268 non-null    int64
 4   Fare        268 non-null    float64
 5   Sex_le      268 non-null    int64
 6   Embarked_Q  268 non-null    int64
 7   Embarked_S  268 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 18.8 KB

None

Info Escalados de Teste
<class 'pandas.core.frame.DataFrame'>
Index: 268 entries, 374 to 228
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Pclass       268 non-null    int64
 1   Age          268 non-null    float64
 2   SibSp        268 non-null    int64
 3   Parch        268 non-null    int64
 4   Fare         268 non-null    float64
 5   Sex_le       268 non-null    int64
 6   Embarked_Q   268 non-null    int64
 7   Embarked_S   268 non-null    int64
 8   Fare_scaled  268 non-null    float64
 9   Age_scaled   268 non-null    float64
dtypes: float64(4), int64(6)
memory usage: 23.0 KB

None

Converta os parâmetros padronizados em um DataFrame e verifique o cabeçalho desse DataFrame para garantir que a transform() funcionou.

In [549]:
print('inverse_transform do Fare')
display(fare_scaler.inverse_transform(X_train_scaled[['Fare_scaled']].head(5)))
display(X_train[['Fare']].head(5))

print('\ninverse_transform do Age')
display(age_scaler.inverse_transform(X_train_scaled[['Age_scaled']].head(5)))
display(X_train[['Age']].head(5))

inverse_transform do Fare

array([[146.5208],
       [ 12.525 ],
       [ 26.3875],
       [ 13.    ],
       [ 34.6542]])

         Fare
195  146.5208
150   12.5250
572   26.3875
134   13.0000
96    34.6542

inverse_transform do Age

array([[58.],
       [51.],
       [36.],
       [25.],
       [71.]])

      Age
195  58.0
150  51.0
572  36.0
134  25.0
96   71.0

## Conclusão

Neste estudo, aplicamos ao dataset do Titanic (891 passageiros, 12 colunas) as etapas de pré-processamento necessárias para deixar os dados prontos para um modelo de classificação da variável `Survived`.

**O que foi feito**
- **Análise inicial:** `info()` e `describe()` mostraram valores ausentes em `Age` (177), `Cabin` (687, cerca de 77% da coluna) e `Embarked` (2). Também mostraram que `Fare` é bastante assimétrica (média 32,2; mediana 14,5; máximo 512,3). Cerca de 38% dos passageiros sobreviveram.
- **Transformação de categóricas:** `Sex` foi codificada com `LabelEncoder` (`Sex_le`) e `Embarked` foi binarizada com `get_dummies` (`Embarked_Q`, `Embarked_S`, tendo C como categoria de referência).
- **Remoção de campos:** `PassengerId`, `Name`, `Ticket` e `Cabin` foram descartados por serem identificadores ou terem excesso de dados faltantes. `Sex` também foi removida após a codificação.
- **Valores nulos:** as idades ausentes foram preenchidas com a mediana de cada grupo (classe × sexo), preservando mais a estrutura dos dados do que uma mediana global.
- **Separação holdout:** os dados foram divididos em 70% para treino (623 linhas) e 30% para teste (268 linhas), com `random_state=111` para reprodutibilidade.
- **Normalização:** `Age` e `Fare` foram padronizadas com `StandardScaler` (média 0 e desvio 1). As demais variáveis foram mantidas, pois são binárias ou categorias/contagens com escala pequena.

**Por que separar treino e teste**
O conjunto de teste simula dados que o modelo nunca viu. Ele serve para estimar o desempenho real do modelo, e essa estimativa só é confiável se o teste não influenciar nenhuma etapa do treinamento.

**Por que o scaler foi ajustado (`fit`) só no treino**
O `StandardScaler` aprende a média e o desvio padrão de cada coluna, então faz parte do "conhecimento" do modelo. Por isso usamos `fit_transform` no treino e apenas `transform` no teste, aplicando a mesma régua aprendida no treino. Se o `fit` usasse também o teste, informação dos dados de avaliação vazaria para o pré-processamento (*data leakage*) e a métrica ficaria otimista. Em um cenário real, um passageiro novo só poderia ser escalado com as estatísticas guardadas do treino.

O resultado confirma o comportamento esperado: no treino, as variáveis escaladas têm média ≈ 0 e desvio ≈ 1; no teste, ficam próximas, mas não exatas (por exemplo, desvio de 1,25 em `Fare_scaled` e de 0,92 em `Age_scaled`). Isso é normal e indica que o teste foi tratado como dado novo. O `inverse_transform` permitiu recuperar os valores originais a partir dos escalados, validando a transformação.

**Limitações**
- `Fare` continua assimétrica após a padronização.

**Próximos passos**
Os dados estão preparados para treinar modelos como regressão logística, KNN, SVM ou redes neurais, que dependem da escala das variáveis. Modelos baseados em árvores (Random Forest, XGBoost) não exigem essa normalização. Em seguida, vale treinar um modelo no conjunto de treino e avaliá-lo no teste, com métricas como acurácia, precisão e recall.